points:
  - {x: -1.80, y:  1.25}
  - {x: -0.45, y: -1.90}
  - {x:  0.30, y:  1.80}
  - {x:  0.00, y:  0.00}
  - {x: -1.15, y:  2.20}
  - {x:  0.85, y: -0.75}
  - {x:  0.40, y: -1.70}
  - {x: -0.60, y:  1.80}
  - {x:  1.10, y:  0.40}
  - {x: -1.15, y:  0.30}
  - {x:  0.65, y:  1.10}
  - {x: -1.60, y: -0.65}
